# Copy from https://github.com/sapphiredev/plugins/blob/main/.github/workflows/release-crosspost.yml
name: Release Crosspost

on:
  release:
    types:
      - published

jobs:
  Crosspost:
    name: Release Crosspost
    runs-on: ubuntu-latest
    steps:
      - name: Parse release name
        id: get_release_name
        run: echo ::set-output name=release_name::${RELEASE:-$TAG}
        env:
          RELEASE: ${{ github.event.release.name }}
          TAG: ${{ github.event.release.tag_name }}

      - name: Send Release Message
        id: crosspost_action
        uses: kludge-cs/gitcord-release-changelogger@ea05f53df33069d711cefce7230d01962b31a865
        with:
          webhook-url: ${{ secrets.RELEASE_WEBHOOK }}
          release-body: ${{ github.event.release.body }}
          release-name: ${{ steps.get_release_name.outputs.release_name }}
